profiler/src/Demos/Samples.BuggyBits/Controllers/CompanyInformationController.cs
// <copyright file="CompanyInformationController.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2022 Datadog, Inc.
// </copyright>

using BuggyBits.Models;
using Microsoft.AspNetCore.Mvc;

namespace BuggyBits.Controllers
{
    public class CompanyInformationController : Controller
    {
        private readonly DataLayer dataLayer;

        public CompanyInformationController(DataLayer dataLayer)
        {
            this.dataLayer = dataLayer;
        }

        public IActionResult Index()
        {
            // bad blocking call
            ViewData["TessGithubPage"] = dataLayer.GetTessGithubPage().Result;

            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            BuggyMail mail = new BuggyMail();
            mail.SendEmail(model.Message, "whocares-at-buggymail");
            return View("Index");
        }
    }
}

profiler/src/Demos/Samples.BuggyBits/Views/CompanyInformation/Index.cshtml
@model ContactViewModel

@{
    ViewData["Title"] = "Company Information";
}

<h2>Company Information</h2>
<p>Buggy Bits was established in 1994 as a one-man company delivering really buggy software and t-shirts noone would ever wear.</p>
<p>
    Since then it has grown into a large organization with over 1754 employees and the main focus for the
    company today is to sell worthless products at horribly high
    prices.
</p>
<p></p>
<p>
   Look at Tess Ferrandez's Github for more details
</p>
<p>
    @Html.Raw(@ViewData["TessGithubPage"]))
</p>
<p></p>
<p><b>Send us a message</b></p>
@using (Html.BeginForm("Contact", "CompanyInformation", FormMethod.Post))
{
    @Html.TextBoxFor(m => m.Message)

    <input type="submit" value="Send" />
}